"""Initial tables

Revision ID: cd97a61c471a
Revises: 
Create Date: 2026-09-15 18:12:16.826990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd97a61c471a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('light_curves',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('mission', sa.String(), nullable=False),
    sa.Column('time_data', sa.JSON(), nullable=False),
    sa.Column('flux_data', sa.JSON(), nullable=False),
    sa.Column('flux_err_data', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_light_curves_target_id'), 'light_curves', ['target_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('light_curve_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['light_curve_id'], ['light_curves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investigations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('candidate_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('investigation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hypotheses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('investigation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('investigation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('hypothesis_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('source_agent', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('supports', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence')
    op.drop_table('hypotheses')
    op.drop_table('agent_runs')
    op.drop_table('investigations')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_light_curves_target_id'), table_name='light_curves')
    op.drop_table('light_curves')
    # ### end Alembic commands ###
